apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - name: flask-app
      targetPort: 5000
      port: 80
      nodePort: 32760
