apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config-map
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    security:
      authorization: enabled
