apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
immutable: false  
data:
  username: admin
  mongodb.conf: |  
    storage:
      dbPath: /data/db  # Sets the MongoDB data storage path
    replication:
      replSetName: "rs0"  # Specifies the name of the MongoDB replica set
